backend:
  name: github
  repo: anunknownc/Fundacion
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/index.md"
        label: "Página Principal"
        name: "index"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }